name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1.3.0
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Build React app
      run: bun run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Update this if your build output directory is different
        # Uncomment the below lines if using custom domain
        # cname: www.yourdomain.com
